# Base configs
baseurl: "/gallery" # the subpath of your site, e.g. /blog
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
google_analytics: ""

# UI configs
title: "天涼好個秋"
subtitle: ""
author: ""
header:
 title: "天涼好個秋"
 subtitle: ""
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""

social_urls:
  twitter: ""
  instagram: ""

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
exif: '[{"tag": "DateTimeOriginal", "icon": "far fa-calendar"}, {"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}]'

exclude:
  - aperture-jekyll-template-main/